setup.py: fix utf8 issue with pypy3
For some reason pypy3 assumes the README.md file's .encoding = 'ANSI_X3.4-1968', instead of UTF8

This yields a nice error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 2372: ordinal not in range(128)

This is around the ohm resistance symbol (omega) in the examples.

Fix it by forcing utf8 encoding when opening the file.

TEST="pypy3 setup.py --long-description" now works